### ISSUE TITLE
LINQPad samples in NuGet packages

### ISSUE THREAD

**Issue by naveensrinivasan** [naveensrinivasan/octokit.net#3]
Implement LINQPad samples in NuGet packages.

http://www.linqpad.net/nugetsamples.aspx
- [x] Implement LINQPad samples 
- [x] Update build to include the sample as nuget package
- [x] Write a test to make sure new check-in's don't break the samples

**Comment by naveensrinivasan** [comment]
Linqpad samples 0053069eab

**Comment by naveensrinivasan** [comment]
Fixed ab4b4257b41b49986a829c934154b4c016f9ef9f

**Comment by sgmoore** [comment]
The current nuget packages are tagged with linqpad-samples, which would lead linqpad users to expect the samples to be downloaded automatically into linqpad, but that does not happen as the packages do not contain the actual linqpad samples.
